name = "roz"
account_id = "343722b0bfef3b2b8521e1a215020408"
workers_dev = false
compatibility_date = "2026-02-02"
main = "src/worker.js"  # Top-level is correct in v4.6+

# Routes
routes = ["roz.odell.house/*"]

# R2 Bucket Bindings
[[r2_buckets]]
binding = "JPG"
bucket_name = "jpg"

[[r2_buckets]]
binding = "JPG_PUBLIC"
bucket_name = "jpg-public"

[[r2_buckets]]
binding = "MP4"
bucket_name = "mp4"

[[r2_buckets]]
binding = "ICON"
bucket_name = "icon"

