name = "roz"
type = "javascript"
account_id = "343722b0bfef3b2b8521e1a215020408"
workers_dev = false
compatibility_date = "2024-02-27"

# Main entry point
main = "src/worker.js" 

# R2 Bucket Bindings
[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "audio"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "image"

[[r2_buckets]]
binding = "IMAGE_PUBLIC_BUCKET"
bucket_name = "image_public"


[[r2_buckets]]
binding = "MP4_BUCKET"
bucket_name = "mp4"

[[r2_buckets]]
binding = "ICON_BUCKET"
bucket_name = "icon"